name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
          # Optional: set if your key has a passphrase
          # ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -p "${SSH_PORT:-22}" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Create deploy directory on VPS
        run: |
          ssh -p "${SSH_PORT:-22}" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" "mkdir -p '$DEPLOY_PATH'"

      - name: Rsync static site to VPS
        run: |
          rsync -az --delete --human-readable \
            -e "ssh -p ${SSH_PORT:-22} -o StrictHostKeyChecking=yes" \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'node_modules/' \
            --exclude 'mockup/' \
            --exclude 'rules/' \
            --exclude 'tasks/' \
            --exclude 'build/' \
            --exclude 'package*.json' \
            --exclude 'postcss.config.js' \
            --exclude 'tailwind.config.js' \
            --exclude 'eslint.config.js' \
            ./ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH"


